// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen4 = NULL;
lv_obj_t * ui_Container8 = NULL;
lv_obj_t * ui_StateScreenTitle = NULL;
lv_obj_t * ui_TextAlgoState = NULL;
lv_obj_t * ui_TextMaterial = NULL;
lv_obj_t * ui_TextDiameter = NULL;
lv_obj_t * ui_sc3TextLeft2 = NULL;
lv_obj_t * ui_TextAlgoStateShow = NULL;
lv_obj_t * ui_TextMaterialShow = NULL;
lv_obj_t * ui_TextDiameterShow = NULL;
// event funtions

// build funtions

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container8 = lv_obj_create(ui_Screen4);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, 246);
    lv_obj_set_height(ui_Container8, 243);
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StateScreenTitle = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_StateScreenTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StateScreenTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StateScreenTitle, -3);
    lv_obj_set_y(ui_StateScreenTitle, -88);
    lv_obj_set_align(ui_StateScreenTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StateScreenTitle, "STATE");
    lv_obj_set_style_text_color(ui_StateScreenTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StateScreenTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StateScreenTitle, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAlgoState = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_TextAlgoState, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextAlgoState, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextAlgoState, -58);
    lv_obj_set_y(ui_TextAlgoState, -48);
    lv_obj_set_align(ui_TextAlgoState, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextAlgoState, "ALGO STATE :");
    lv_obj_set_style_text_color(ui_TextAlgoState, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextAlgoState, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAlgoState, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextMaterial = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_TextMaterial, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextMaterial, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextMaterial, -61);
    lv_obj_set_y(ui_TextMaterial, -2);
    lv_obj_set_align(ui_TextMaterial, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextMaterial, "MATERIAL :");
    lv_obj_set_style_text_color(ui_TextMaterial, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextMaterial, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextMaterial, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextDiameter = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_TextDiameter, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextDiameter, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextDiameter, -61);
    lv_obj_set_y(ui_TextDiameter, 42);
    lv_obj_set_align(ui_TextDiameter, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextDiameter, "DIAMETER :");
    lv_obj_set_style_text_color(ui_TextDiameter, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextDiameter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextDiameter, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sc3TextLeft2 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_sc3TextLeft2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sc3TextLeft2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sc3TextLeft2, -90);
    lv_obj_set_y(ui_sc3TextLeft2, 104);
    lv_obj_set_align(ui_sc3TextLeft2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sc3TextLeft2, "LEFT");
    lv_obj_set_style_text_color(ui_sc3TextLeft2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sc3TextLeft2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAlgoStateShow = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_TextAlgoStateShow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextAlgoStateShow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextAlgoStateShow, 63);
    lv_obj_set_y(ui_TextAlgoStateShow, -50);
    lv_obj_set_align(ui_TextAlgoStateShow, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextAlgoStateShow, "0");
    lv_obj_set_style_text_color(ui_TextAlgoStateShow, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextAlgoStateShow, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAlgoStateShow, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextMaterialShow = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_TextMaterialShow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextMaterialShow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextMaterialShow, 63);
    lv_obj_set_y(ui_TextMaterialShow, -1);
    lv_obj_set_align(ui_TextMaterialShow, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextMaterialShow, "0");
    lv_obj_set_style_text_color(ui_TextMaterialShow, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextMaterialShow, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextMaterialShow, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextDiameterShow = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_TextDiameterShow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextDiameterShow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextDiameterShow, 63);
    lv_obj_set_y(ui_TextDiameterShow, 43);
    lv_obj_set_align(ui_TextDiameterShow, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextDiameterShow, "0");
    lv_obj_set_style_text_color(ui_TextDiameterShow, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextDiameterShow, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextDiameterShow, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen4_screen_destroy(void)
{
    if(ui_Screen4) lv_obj_del(ui_Screen4);

    // NULL screen variables
    ui_Screen4 = NULL;
    ui_Container8 = NULL;
    ui_StateScreenTitle = NULL;
    ui_TextAlgoState = NULL;
    ui_TextMaterial = NULL;
    ui_TextDiameter = NULL;
    ui_sc3TextLeft2 = NULL;
    ui_TextAlgoStateShow = NULL;
    ui_TextMaterialShow = NULL;
    ui_TextDiameterShow = NULL;

}
