// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN4_H
#define UI_SCREEN4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen4
extern void ui_Screen4_screen_init(void);
extern void ui_Screen4_screen_destroy(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_StateScreenTitle;
extern lv_obj_t * ui_TextAlgoState;
extern lv_obj_t * ui_TextMaterial;
extern lv_obj_t * ui_TextDiameter;
extern lv_obj_t * ui_sc3TextLeft2;
extern lv_obj_t * ui_TextAlgoStateShow;
extern lv_obj_t * ui_TextMaterialShow;
extern lv_obj_t * ui_TextDiameterShow;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

