// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_SetScreenTitle;
extern lv_obj_t * ui_ButtonReset;
extern lv_obj_t * ui_LabelReset;
extern lv_obj_t * ui_ButtonZeroDriftLearn;
extern lv_obj_t * ui_LabelZeroDriftLearn;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_sc3TextLeft;
extern lv_obj_t * ui_sc3TextK3;
extern lv_obj_t * ui_sc3TextK2;
extern lv_obj_t * ui_sc3TextRight;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

