// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_ConfigScreenTitle;
extern lv_obj_t * ui_diameterTitle;
extern lv_obj_t * ui_diameterDropDown;
extern lv_obj_t * ui_materialTitle;
extern lv_obj_t * ui_materialDropDown;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_sc2TextLeft;
extern lv_obj_t * ui_sc2TextK3;
extern lv_obj_t * ui_sc2TextK2;
extern lv_obj_t * ui_sc2TextRight;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

