// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_Arc1 = NULL;
lv_obj_t * ui_totalFlowIndicator = NULL;
lv_obj_t * ui_SQIndicator = NULL;
lv_obj_t * ui_FlowVector = NULL;
lv_obj_t * ui_instFlowIndicator = NULL;
lv_obj_t * ui_sc1TextRight = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container1 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 246);
    lv_obj_set_height(ui_Container1, 243);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc1 = lv_arc_create(ui_Container1);
    lv_obj_set_width(ui_Arc1, 150);
    lv_obj_set_height(ui_Arc1, 150);
    lv_obj_set_x(ui_Arc1, -2);
    lv_obj_set_y(ui_Arc1, -3);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc1, 50);

    lv_obj_set_style_bg_color(ui_Arc1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_totalFlowIndicator = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_totalFlowIndicator, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_totalFlowIndicator, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_totalFlowIndicator, -4);
    lv_obj_set_y(ui_totalFlowIndicator, 65);
    lv_obj_set_align(ui_totalFlowIndicator, LV_ALIGN_CENTER);
    lv_label_set_text(ui_totalFlowIndicator, "0");
    lv_obj_set_style_text_color(ui_totalFlowIndicator, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_totalFlowIndicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SQIndicator = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_SQIndicator, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SQIndicator, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SQIndicator, -90);
    lv_obj_set_y(ui_SQIndicator, -98);
    lv_obj_set_align(ui_SQIndicator, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SQIndicator, "0");
    lv_obj_set_style_text_color(ui_SQIndicator, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SQIndicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FlowVector = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_FlowVector, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FlowVector, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FlowVector, -3);
    lv_obj_set_y(ui_FlowVector, -1);
    lv_obj_set_align(ui_FlowVector, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FlowVector, "0");
    lv_obj_set_style_text_color(ui_FlowVector, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FlowVector, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_instFlowIndicator = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_instFlowIndicator, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_instFlowIndicator, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_instFlowIndicator, -4);
    lv_obj_set_y(ui_instFlowIndicator, 86);
    lv_obj_set_align(ui_instFlowIndicator, LV_ALIGN_CENTER);
    lv_label_set_text(ui_instFlowIndicator, "0");
    lv_obj_set_style_text_color(ui_instFlowIndicator, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_instFlowIndicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sc1TextRight = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_sc1TextRight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sc1TextRight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sc1TextRight, 89);
    lv_obj_set_y(ui_sc1TextRight, 107);
    lv_obj_set_align(ui_sc1TextRight, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sc1TextRight, "RIGHT");
    lv_obj_set_style_text_color(ui_sc1TextRight, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sc1TextRight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Container1 = NULL;
    ui_Arc1 = NULL;
    ui_totalFlowIndicator = NULL;
    ui_SQIndicator = NULL;
    ui_FlowVector = NULL;
    ui_instFlowIndicator = NULL;
    ui_sc1TextRight = NULL;

}
