// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_ConfigScreenTitle = NULL;
lv_obj_t * ui_diameterTitle = NULL;
lv_obj_t * ui_diameterDropDown = NULL;
lv_obj_t * ui_materialTitle = NULL;
lv_obj_t * ui_materialDropDown = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_sc2TextLeft = NULL;
lv_obj_t * ui_sc2TextK3 = NULL;
lv_obj_t * ui_sc2TextK2 = NULL;
lv_obj_t * ui_sc2TextRight = NULL;
// event funtions

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container3 = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 246);
    lv_obj_set_height(ui_Container3, 243);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Container3);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 222);
    lv_obj_set_height(ui_Container2, 193);
    lv_obj_set_x(ui_Container2, 0);
    lv_obj_set_y(ui_Container2, -18);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ConfigScreenTitle = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_ConfigScreenTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConfigScreenTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ConfigScreenTitle, -9);
    lv_obj_set_y(ui_ConfigScreenTitle, -74);
    lv_obj_set_align(ui_ConfigScreenTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConfigScreenTitle, "CONFIG");
    lv_obj_set_style_text_color(ui_ConfigScreenTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConfigScreenTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConfigScreenTitle, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_diameterTitle = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_diameterTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_diameterTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_diameterTitle, -62);
    lv_obj_set_y(ui_diameterTitle, 35);
    lv_obj_set_align(ui_diameterTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_diameterTitle, "Diameter");
    lv_obj_set_style_text_color(ui_diameterTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_diameterTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_diameterTitle, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_diameterDropDown = lv_dropdown_create(ui_Container2);
    lv_dropdown_set_options(ui_diameterDropDown, "DN35\nDN25\nDN20\nDN15\nDN10");
    lv_obj_set_width(ui_diameterDropDown, 112);
    lv_obj_set_height(ui_diameterDropDown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_diameterDropDown, 45);
    lv_obj_set_y(ui_diameterDropDown, 34);
    lv_obj_set_align(ui_diameterDropDown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_diameterDropDown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_bg_color(ui_diameterDropDown, lv_color_hex(0x9A9A9A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_diameterDropDown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_diameterDropDown), lv_color_hex(0x9A9A9A),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_diameterDropDown), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_materialTitle = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_materialTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_materialTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_materialTitle, -61);
    lv_obj_set_y(ui_materialTitle, -25);
    lv_obj_set_align(ui_materialTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_materialTitle, "Material");
    lv_obj_set_style_text_color(ui_materialTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_materialTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_materialTitle, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_materialDropDown = lv_dropdown_create(ui_Container2);
    lv_dropdown_set_options(ui_materialDropDown, "Metal\nPlastic\nAluminum");
    lv_obj_set_width(ui_materialDropDown, 112);
    lv_obj_set_height(ui_materialDropDown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_materialDropDown, 43);
    lv_obj_set_y(ui_materialDropDown, -28);
    lv_obj_set_align(ui_materialDropDown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_materialDropDown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_bg_color(ui_materialDropDown, lv_color_hex(0x9A9A9A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_materialDropDown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_materialDropDown), lv_color_hex(0x9A9A9A),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_materialDropDown), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_Container3);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 231);
    lv_obj_set_height(ui_Container4, 17);
    lv_obj_set_x(ui_Container4, 0);
    lv_obj_set_y(ui_Container4, 105);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sc2TextLeft = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_sc2TextLeft, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sc2TextLeft, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sc2TextLeft, -89);
    lv_obj_set_y(ui_sc2TextLeft, 3);
    lv_obj_set_align(ui_sc2TextLeft, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sc2TextLeft, "LEFT");
    lv_obj_set_style_text_color(ui_sc2TextLeft, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sc2TextLeft, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sc2TextK3 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_sc2TextK3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sc2TextK3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sc2TextK3, -29);
    lv_obj_set_y(ui_sc2TextK3, 3);
    lv_obj_set_align(ui_sc2TextK3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sc2TextK3, "METAL");
    lv_obj_set_style_text_color(ui_sc2TextK3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sc2TextK3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sc2TextK2 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_sc2TextK2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sc2TextK2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sc2TextK2, 28);
    lv_obj_set_y(ui_sc2TextK2, 2);
    lv_obj_set_align(ui_sc2TextK2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sc2TextK2, "D");
    lv_obj_set_style_text_color(ui_sc2TextK2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sc2TextK2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sc2TextRight = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_sc2TextRight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sc2TextRight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sc2TextRight, 84);
    lv_obj_set_y(ui_sc2TextRight, 2);
    lv_obj_set_align(ui_sc2TextRight, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sc2TextRight, "RIGHT");
    lv_obj_set_style_text_color(ui_sc2TextRight, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sc2TextRight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Container3 = NULL;
    ui_Container2 = NULL;
    ui_ConfigScreenTitle = NULL;
    ui_diameterTitle = NULL;
    ui_diameterDropDown = NULL;
    ui_materialTitle = NULL;
    ui_materialDropDown = NULL;
    ui_Container4 = NULL;
    ui_sc2TextLeft = NULL;
    ui_sc2TextK3 = NULL;
    ui_sc2TextK2 = NULL;
    ui_sc2TextRight = NULL;

}
