// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_Container5 = NULL;
lv_obj_t * ui_SetScreenTitle = NULL;
lv_obj_t * ui_ButtonReset = NULL;
lv_obj_t * ui_LabelReset = NULL;
lv_obj_t * ui_ButtonZeroDriftLearn = NULL;
lv_obj_t * ui_LabelZeroDriftLearn = NULL;
lv_obj_t * ui_Container7 = NULL;
lv_obj_t * ui_sc3TextLeft = NULL;
lv_obj_t * ui_sc3TextK3 = NULL;
lv_obj_t * ui_sc3TextK2 = NULL;
lv_obj_t * ui_sc3TextRight = NULL;
// event funtions

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container5 = lv_obj_create(ui_Screen3);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 246);
    lv_obj_set_height(ui_Container5, 243);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetScreenTitle = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_SetScreenTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetScreenTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SetScreenTitle, -3);
    lv_obj_set_y(ui_SetScreenTitle, -88);
    lv_obj_set_align(ui_SetScreenTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SetScreenTitle, "SET");
    lv_obj_set_style_text_color(ui_SetScreenTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SetScreenTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SetScreenTitle, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonReset = lv_btn_create(ui_Container5);
    lv_obj_set_width(ui_ButtonReset, 140);
    lv_obj_set_height(ui_ButtonReset, 50);
    lv_obj_set_x(ui_ButtonReset, 1);
    lv_obj_set_y(ui_ButtonReset, -45);
    lv_obj_set_align(ui_ButtonReset, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonReset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonReset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonReset, lv_color_hex(0x1758A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonReset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ButtonReset, lv_color_hex(0x060606), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelReset = lv_label_create(ui_ButtonReset);
    lv_obj_set_width(ui_LabelReset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelReset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelReset, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelReset, "Reset");

    ui_ButtonZeroDriftLearn = lv_btn_create(ui_Container5);
    lv_obj_set_width(ui_ButtonZeroDriftLearn, 138);
    lv_obj_set_height(ui_ButtonZeroDriftLearn, 50);
    lv_obj_set_x(ui_ButtonZeroDriftLearn, 2);
    lv_obj_set_y(ui_ButtonZeroDriftLearn, 26);
    lv_obj_set_align(ui_ButtonZeroDriftLearn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonZeroDriftLearn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonZeroDriftLearn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelZeroDriftLearn = lv_label_create(ui_ButtonZeroDriftLearn);
    lv_obj_set_width(ui_LabelZeroDriftLearn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelZeroDriftLearn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelZeroDriftLearn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelZeroDriftLearn, "Learn Zero Drift");

    ui_Container7 = lv_obj_create(ui_Container5);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, 231);
    lv_obj_set_height(ui_Container7, 17);
    lv_obj_set_x(ui_Container7, 0);
    lv_obj_set_y(ui_Container7, 105);
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sc3TextLeft = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_sc3TextLeft, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sc3TextLeft, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sc3TextLeft, -89);
    lv_obj_set_y(ui_sc3TextLeft, 3);
    lv_obj_set_align(ui_sc3TextLeft, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sc3TextLeft, "LEFT");
    lv_obj_set_style_text_color(ui_sc3TextLeft, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sc3TextLeft, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sc3TextK3 = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_sc3TextK3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sc3TextK3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sc3TextK3, -39);
    lv_obj_set_y(ui_sc3TextK3, 3);
    lv_obj_set_align(ui_sc3TextK3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sc3TextK3, "RESET");
    lv_obj_set_style_text_color(ui_sc3TextK3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sc3TextK3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sc3TextK2 = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_sc3TextK2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sc3TextK2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sc3TextK2, 19);
    lv_obj_set_y(ui_sc3TextK2, 2);
    lv_obj_set_align(ui_sc3TextK2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sc3TextK2, "DRIFT");
    lv_obj_set_style_text_color(ui_sc3TextK2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sc3TextK2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sc3TextRight = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_sc3TextRight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sc3TextRight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sc3TextRight, 84);
    lv_obj_set_y(ui_sc3TextRight, 2);
    lv_obj_set_align(ui_sc3TextRight, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sc3TextRight, "RIGHT");
    lv_obj_set_style_text_color(ui_sc3TextRight, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sc3TextRight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_Container5 = NULL;
    ui_SetScreenTitle = NULL;
    ui_ButtonReset = NULL;
    ui_LabelReset = NULL;
    ui_ButtonZeroDriftLearn = NULL;
    ui_LabelZeroDriftLearn = NULL;
    ui_Container7 = NULL;
    ui_sc3TextLeft = NULL;
    ui_sc3TextK3 = NULL;
    ui_sc3TextK2 = NULL;
    ui_sc3TextRight = NULL;

}
