#include "app_config.h"

/*********************宏定义部分*********************/
#if RCT6
// 如果要用KEY_SW1的宏定义
#if USE_KEY_SW1
// SW1连在PA8上，按下的时候电压拉低
#define SW1_KEY_PIN GPIO_PIN_8
#define SW1_KEY_GPIO_PORT GPIOA
#define SW1_KEY_GPIO_CLK RCU_GPIOA
#define SW1_KEY_EXTI_LINE EXTI_8
#define SW1_KEY_EXTI_PORT_SOURCE GPIO_PORT_SOURCE_GPIOA
#define SW1_KEY_EXTI_PIN_SOURCE GPIO_PIN_SOURCE_8
#define SW1_KEY_EXTI_IRQn EXTI5_9_IRQn

#endif

#if USE_4KEY
// 按下的时候电压拉低
/* K1 -> PA1 */
#define K1_KEY_PIN GPIO_PIN_1
#define K1_KEY_GPIO_PORT GPIOA
#define K1_KEY_GPIO_CLK RCU_GPIOA
#define K1_KEY_EXTI_LINE EXTI_1
#define K1_KEY_EXTI_PORT_SOURCE GPIO_PORT_SOURCE_GPIOA
#define K1_KEY_EXTI_PIN_SOURCE GPIO_PIN_SOURCE_1
#define K1_KEY_EXTI_IRQn EXTI1_IRQn

/* K2 -> PA2 */
#define K2_KEY_PIN GPIO_PIN_2
#define K2_KEY_GPIO_PORT GPIOA
#define K2_KEY_GPIO_CLK RCU_GPIOA
#define K2_KEY_EXTI_LINE EXTI_2
#define K2_KEY_EXTI_PORT_SOURCE GPIO_PORT_SOURCE_GPIOA
#define K2_KEY_EXTI_PIN_SOURCE GPIO_PIN_SOURCE_2
#define K2_KEY_EXTI_IRQn EXTI2_IRQn

/* K3 -> PA3 */
#define K3_KEY_PIN GPIO_PIN_3
#define K3_KEY_GPIO_PORT GPIOA
#define K3_KEY_GPIO_CLK RCU_GPIOA
#define K3_KEY_EXTI_LINE EXTI_3
#define K3_KEY_EXTI_PORT_SOURCE GPIO_PORT_SOURCE_GPIOA
#define K3_KEY_EXTI_PIN_SOURCE GPIO_PIN_SOURCE_3
#define K3_KEY_EXTI_IRQn EXTI3_IRQn

/* K4 -> PA4 */
#define K4_KEY_PIN GPIO_PIN_4
#define K4_KEY_GPIO_PORT GPIOA
#define K4_KEY_GPIO_CLK RCU_GPIOA
#define K4_KEY_EXTI_LINE EXTI_4
#define K4_KEY_EXTI_PORT_SOURCE GPIO_PORT_SOURCE_GPIOA
#define K4_KEY_EXTI_PIN_SOURCE GPIO_PIN_SOURCE_4
#define K4_KEY_EXTI_IRQn EXTI4_IRQn

#endif

typedef enum
{
    KEY_EVENT_NONE = 0,
    KEY_EVENT_K1,
    KEY_EVENT_K2,
    KEY_EVENT_K3,
    KEY_EVENT_K4
} key_event_t;

#endif